import { TarjetaProducto } from "../../app/models/tarjeta-producto";
import { ProductoListadoCarritoCompras } from "../../app/modules/carrito-compras/models/producto-listado-carrito-compras";

export const TARJETAS_PRODUCTOS_BUSQUEDA: TarjetaProducto[] = [
    {
        sku: 'DCATO19939',
        srcImg: 'assets/imagenes/pagina-principal/ofertas/radiador.svg',
        descripcionProducto: 'Radiador agricola tractor Case 580 k Aluminio/Aluminio TM',
        precio: '$ 1,842',
        oferta: '$ 1,842',
        tieneOferta: true,
        ranking: '4.9',
    },
    {
        sku: 'DCATO19939',
        srcImg: 'assets/imagenes/pagina-principal/ofertas/aspas.svg',
        descripcionProducto: 'Aspas para ventilador Mazda B20000, B22000',
        precio: '$ 1,842',
        oferta: '$ 1,842',
        tieneOferta: false,
        ranking: '4.9',
    },
    {
        sku: 'DCATO19939',
        srcImg: 'assets/imagenes/pagina-principal/ofertas/escape.svg',
        descripcionProducto: 'Escape resonador mofle',
        precio: '$ 1,842',
        oferta: '$ 1,842',
        tieneOferta: true,
        ranking: '4.9',
    },
    {
        sku: 'DCATO19939',
        srcImg: 'assets/imagenes/pagina-principal/ofertas/carter.svg',
        descripcionProducto: 'Carter aceite Mazda 6 2.5, 20009 a 2010 aluminio',
        precio: '$ 1,842',
        oferta: '$ 1,842',
        tieneOferta: true,
        ranking: '4.9',
    },
    {
        sku: 'DCATO19939',
        srcImg: 'assets/imagenes/pagina-principal/ofertas/bujias.svg',
        descripcionProducto: 'Kit 5 Bujias Ngk Platino Vw Jetta Mk6 Bora Beetle Motor 2.5l',
        precio: '$ 1,842',
        oferta: '$ 1,842',
        tieneOferta: true,
        ranking: '4.9',
    },
    {
        sku: 'DCATO19939',
        srcImg: 'assets/imagenes/pagina-principal/ofertas/radiador.svg',
        descripcionProducto: 'Radiador agricola tractor Case 580 k Aluminio/Aluminio TM',
        precio: '$ 1,842',
        oferta: '$ 1,842',
        tieneOferta: true,
        ranking: '4.9',
    },
    {
        sku: 'DCATO19939',
        srcImg: 'assets/imagenes/pagina-principal/ofertas/aspas.svg',
        descripcionProducto: 'Aspas para ventilador Mazda B20000, B22000',
        precio: '$ 1,842',
        oferta: '$ 1,842',
        tieneOferta: false,
        ranking: '4.9',
    },
    {
        sku: 'DCATO19939',
        srcImg: 'assets/imagenes/pagina-principal/ofertas/escape.svg',
        descripcionProducto: 'Escape resonador mofle',
        precio: '$ 1,842',
        oferta: '$ 1,842',
        tieneOferta: true,
        ranking: '4.9',
    },
    {
        sku: 'DCATO19939',
        srcImg: 'assets/imagenes/pagina-principal/ofertas/carter.svg',
        descripcionProducto: 'Carter aceite Mazda 6 2.5, 20009 a 2010 aluminio',
        precio: '$ 1,842',
        oferta: '$ 1,842',
        tieneOferta: true,
        ranking: '4.9',
    },
    {
        sku: 'DCATO19939',
        srcImg: 'assets/imagenes/pagina-principal/ofertas/bujias.svg',
        descripcionProducto: 'Kit 5 Bujias Ngk Platino Vw Jetta Mk6 Bora Beetle Motor 2.5l',
        precio: '$ 1,842',
        oferta: '$ 1,842',
        tieneOferta: true,
        ranking: '4.9',
    },
    {
        sku: 'DCATO19939',
        srcImg: 'assets/imagenes/pagina-principal/ofertas/radiador.svg',
        descripcionProducto: 'Radiador agricola tractor Case 580 k Aluminio/Aluminio TM',
        precio: '$ 1,842',
        oferta: '$ 1,842',
        tieneOferta: true,
        ranking: '4.9',
    },
    {
        sku: 'DCATO19939',
        srcImg: 'assets/imagenes/pagina-principal/ofertas/aspas.svg',
        descripcionProducto: 'Aspas para ventilador Mazda B20000, B22000',
        precio: '$ 1,842',
        oferta: '$ 1,842',
        tieneOferta: false,
        ranking: '4.9',
    },
    {
        sku: 'DCATO19939',
        srcImg: 'assets/imagenes/pagina-principal/ofertas/escape.svg',
        descripcionProducto: 'Escape resonador mofle',
        precio: '$ 1,842',
        oferta: '$ 1,842',
        tieneOferta: true,
        ranking: '4.9',
    },
    {
        sku: 'DCATO19939',
        srcImg: 'assets/imagenes/pagina-principal/ofertas/carter.svg',
        descripcionProducto: 'Carter aceite Mazda 6 2.5, 20009 a 2010 aluminio',
        precio: '$ 1,842',
        oferta: '$ 1,842',
        tieneOferta: true,
        ranking: '4.9',
    },
    {
        sku: 'DCATO19939',
        srcImg: 'assets/imagenes/pagina-principal/ofertas/bujias.svg',
        descripcionProducto: 'Kit 5 Bujias Ngk Platino Vw Jetta Mk6 Bora Beetle Motor 2.5l',
        precio: '$ 1,842',
        oferta: '$ 1,842',
        tieneOferta: true,
        ranking: '4.9',
    },
    {
        sku: 'DCATO19939',
        srcImg: 'assets/imagenes/pagina-principal/ofertas/radiador.svg',
        descripcionProducto: 'Radiador agricola tractor Case 580 k Aluminio/Aluminio TM',
        precio: '$ 1,842',
        oferta: '$ 1,842',
        tieneOferta: true,
        ranking: '4.9',
    },
    {
        sku: 'DCATO19939',
        srcImg: 'assets/imagenes/pagina-principal/ofertas/aspas.svg',
        descripcionProducto: 'Aspas para ventilador Mazda B20000, B22000',
        precio: '$ 1,842',
        oferta: '$ 1,842',
        tieneOferta: false,
        ranking: '4.9',
    },
    {
        sku: 'DCATO19939',
        srcImg: 'assets/imagenes/pagina-principal/ofertas/escape.svg',
        descripcionProducto: 'Escape resonador mofle',
        precio: '$ 1,842',
        oferta: '$ 1,842',
        tieneOferta: true,
        ranking: '4.9',
    },
    {
        sku: 'DCATO19939',
        srcImg: 'assets/imagenes/pagina-principal/ofertas/carter.svg',
        descripcionProducto: 'Carter aceite Mazda 6 2.5, 20009 a 2010 aluminio',
        precio: '$ 1,842',
        oferta: '$ 1,842',
        tieneOferta: true,
        ranking: '4.9',
    },
    {
        sku: 'DCATO19939',
        srcImg: 'assets/imagenes/pagina-principal/ofertas/bujias.svg',
        descripcionProducto: 'Kit 5 Bujias Ngk Platino Vw Jetta Mk6 Bora Beetle Motor 2.5l',
        precio: '$ 1,842',
        oferta: '$ 1,842',
        tieneOferta: true,
        ranking: '4.9',
    },
]


export const LISTADO_PRODUCTOS_CARRITO_COMPRAS: ProductoListadoCarritoCompras[] = [
    {
        srcImg: 'assets/imagenes/carrito-compras/imagen-producto-carrito.svg',
        descripcion: 'VEMO Bujía de encendido Q+, calidad de primer equipo',
        precio: '$ 250.00 MXN',
        cantidad: 1,
        stock: 10,
    },
    {
        srcImg: 'assets/imagenes/carrito-compras/imagen-producto-carrito.svg',
        descripcion: 'VEMO Bujía de encendido Q+, calidad de primer equipo',
        precio: '$ 250.00 MXN',
        cantidad: 1,
        stock: 10,
    },
    {
        srcImg: 'assets/imagenes/carrito-compras/imagen-producto-carrito.svg',
        descripcion: 'VEMO Bujía de encendido Q+, calidad de primer equipo',
        precio: '$ 250.00 MXN',
        cantidad: 1,
        stock: 10,
    },
    {
        srcImg: 'assets/imagenes/carrito-compras/imagen-producto-carrito.svg',
        descripcion: 'VEMO Bujía de encendido Q+, calidad de primer equipo',
        precio: '$ 250.00 MXN',
        cantidad: 1,
        stock: 10,
    }
]